name: "Stolovka"

settings:
  base:
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    CLANG_ANALYZER_LOCALIZABILITY_EMPTY_CONTEXT: YES
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES

options:
  deploymentTarget:
    iOS: 15.0

attributes:
  ORGANIZATIONNAME: "Владислав Лисянский"

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.0.1
  Moya:
    url: https://github.com/Moya/Moya
    from: 15.0.0

targets:
  Stolovka:
    platform: iOS
    type: application
    sources:
      - path: "Stolovka"
    dependencies:
      - package: SnapKit
      - package: Moya

    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DISPLAY_NAME: "Stolovka"
        INFOPLIST_FILE: "Stolovka/Info.plist"
        OTHER_LDFLAGS: $(inherited) -ObjC
        DEVELOPMENT_TEAM: SGM5527A99
        PRODUCT_BUNDLE_IDENTIFIER: com.tr1ckyf0x.stolovka
        CODE_SIGN_STYLE: Manual
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          PROVISIONING_PROFILE_SPECIFIER: "Stolovka Development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "Stolovka AppStore"
