configurations:
  - sources:
    - Sources
    templates:
    - ../../../Templates/AutoMockable.stencil
    output:
      Tests/CartScreenTests/Mock
    args:
      autoMockableTestableImports:
        - CartScreen
      autoMockableImports: 
        - Models